services:
  api:
    build: .
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-123456789}@db:5432/${DB_NAME:-promo_code_systems}

  db:
    image: postgres:17.7
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-promo_code_systems}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456789}
    ports:
      - '5460:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
