/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Academies {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  institutionId: string;
  name: string;
  parentId: string | null;
  shortName: string | null;
  type: string;
}

export interface CardClassrooms {
  cardId: string;
  classroomId: string;
}

export interface Cards {
  createdAt: Generated<Timestamp>;
  createdById: string;
  dayId: string;
  id: Generated<string>;
  institutionId: string;
  isException: Generated<boolean>;
  note: string | null;
  periodId: string;
  subjectSettingsId: string;
  termId: string;
  topicId: string | null;
  weekId: string;
  yearId: string;
}

export interface Classes {
  academyId: string;
  color: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdById: string;
  gradeId: string;
  id: Generated<string>;
  institutionId: string;
  name: string;
  shortName: string;
  yearId: string;
}

export interface Classrooms {
  color: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdById: string;
  id: Generated<string>;
  institutionId: string;
  name: string;
  shortName: string;
}

export interface Daysdefs {
  createdAt: Generated<Timestamp>;
  days: string;
  id: Generated<string>;
  institutionId: string;
  isVisible: Generated<boolean>;
  name: string;
  shortName: string;
  yearId: string;
}

export interface Grades {
  createdAt: Generated<Timestamp>;
  createdById: string;
  grade: string;
  id: Generated<string>;
  institutionId: string;
  name: string;
  shortName: string | null;
}

export interface Groups {
  classId: string;
  createdAt: Generated<Timestamp>;
  createdById: string;
  divisiontag: string;
  entireclass: Generated<boolean>;
  id: Generated<string>;
  name: string;
}

export interface GroupStudents {
  groupId: string;
  studentId: string;
}

export interface Info {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  logo: string | null;
  title: string;
}

export interface Institutions {
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  locationId: string;
  name: string;
  shortName: string | null;
}

export interface Locations {
  id: Generated<string>;
  name: string;
  parentId: string | null;
}

export interface News {
  content: string | null;
  createdAt: Generated<Timestamp>;
  createdById: string;
  id: Generated<string>;
  image: string | null;
  institutionId: string | null;
  title: string;
}

export interface Periods {
  createdAt: Generated<Timestamp>;
  endTime: Timestamp;
  id: Generated<string>;
  institutionId: string;
  name: string;
  period: string;
  shortName: string;
  startTime: Timestamp;
  yearId: string;
}

export interface Permissions {
  action: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  module: string;
  userId: string;
}

export interface PhoneVerifications {
  attempt: Generated<number>;
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  phone: string;
}

export interface Quotes {
  author: string | null;
  createdAt: Generated<Timestamp>;
  createdById: string;
  id: Generated<string>;
  institutionId: string | null;
  title: string;
}

export interface StudentAbsence {
  cardId: string;
  closedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  studentId: string;
  type: string;
}

export interface Students {
  classId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  studyEndDate: Timestamp | null;
  studyStartDate: Timestamp | null;
  userId: string;
}

export interface Subjects {
  color: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  institutionId: string;
  name: string;
  shortName: string;
}

export interface SubjectSettings {
  academyId: string;
  createdAt: Generated<Timestamp>;
  createdById: string;
  daysdefId: string;
  id: Generated<string>;
  periodspercard: string;
  periodsperweek: string;
  seminargroup: string | null;
  subjectId: string;
  subjectSettingsTypeId: string;
  termsdefId: string;
  weeksdefId: string;
}

export interface SubjectSettingsClasses {
  classId: string;
  subjectSettingsId: string;
}

export interface SubjectSettingsClassrooms {
  classroomId: string;
  subjectSettingsId: string;
}

export interface SubjectSettingsGroups {
  groupId: string;
  subjectSettingsId: string;
}

export interface SubjectSettingsTeachers {
  subjectSettingsId: string;
  teacherId: string;
}

export interface SubjectSettingsTypes {
  id: Generated<string>;
  institutionId: string;
  name: string;
}

export interface Teachers {
  color: string;
  createdAt: Generated<Timestamp>;
  gender: string;
  id: Generated<string>;
  shortName: string;
  userId: string;
}

export interface TeachersClasses {
  classId: string;
  teacherId: string;
}

export interface TeachersClassrooms {
  classroomId: string;
  teacherId: string;
}

export interface Termsdefs {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  institutionId: string;
  isVisible: Generated<boolean>;
  name: string;
  shortName: string;
  terms: string;
  yearId: string;
}

export interface Topics {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  orderIndex: Generated<number>;
  subjectId: string;
}

export interface Users {
  academyId: string | null;
  avatar: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string | null;
  fcmToken: string | null;
  fullName: string;
  id: Generated<string>;
  institutionId: string | null;
  password: string;
  phone: string;
  role: string;
}

export interface Weeksdefs {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  institutionId: string;
  isVisible: Generated<boolean>;
  name: string;
  shortName: string;
  weeks: string;
  yearId: string;
}

export interface Years {
  createdAt: Generated<Timestamp>;
  from: number;
  id: Generated<string>;
  title: string;
  to: number;
}

export interface DB {
  academies: Academies;
  card_classrooms: CardClassrooms;
  cards: Cards;
  classes: Classes;
  classrooms: Classrooms;
  daysdefs: Daysdefs;
  grades: Grades;
  group_students: GroupStudents;
  groups: Groups;
  info: Info;
  institutions: Institutions;
  locations: Locations;
  news: News;
  periods: Periods;
  permissions: Permissions;
  phone_verifications: PhoneVerifications;
  quotes: Quotes;
  student_absence: StudentAbsence;
  students: Students;
  subject_settings: SubjectSettings;
  subject_settings_classes: SubjectSettingsClasses;
  subject_settings_classrooms: SubjectSettingsClassrooms;
  subject_settings_groups: SubjectSettingsGroups;
  subject_settings_teachers: SubjectSettingsTeachers;
  subject_settings_types: SubjectSettingsTypes;
  subjects: Subjects;
  teachers: Teachers;
  teachers_classes: TeachersClasses;
  teachers_classrooms: TeachersClassrooms;
  termsdefs: Termsdefs;
  topics: Topics;
  users: Users;
  weeksdefs: Weeksdefs;
  years: Years;
}
