/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Promocodes {
  id: Generated<string>;
  code: string;
  discount: number;
  maxUses: number;
  usedCount: Generated<number>;
  expiresAt: Timestamp;
  createdAt: Generated<Timestamp>;
}

export interface Activations {
  id: Generated<string>;
  promocodeId: string;
  email: string;
  createdAt: Generated<Timestamp>;
}

export interface DB {
  promocodes: Promocodes;
  activations: Activations;
}
